# Generated by Django 4.1.2 on 2022-10-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('birth_date', models.DateField()),
                ('points', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
