# Generated by Django 4.1.2 on 2022-11-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_manager_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
