# Generated by Django 4.1.2 on 2022-12-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_manager_id_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_type',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
