# Generated by Django 4.1.2 on 2022-12-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customer_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AddField(
            model_name='manager',
            name='user_type',
            field=models.CharField(default='Manager', max_length=50),
        ),
    ]
