# Generated by Django 4.1.2 on 2022-11-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0002_remove_order_date_order_date_time_alter_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='date_time',
        ),
    ]
