# Generated by Django 4.1.2 on 2022-12-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_employee_user_type_manager_user_type'),
        ('Objects', '0003_rename_date_review_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.employee'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Objects.order'),
        ),
    ]
