# Generated by Django 4.1.2 on 2022-12-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Objects', '0005_rename_order_id_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Objects.order'),
        ),
    ]
